# Generated by Django 5.0.3 on 2024-03-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_id',
            new_name='item',
        ),
    ]
