# Generated by Django 5.0.3 on 2024-03-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddItem',
        ),
    ]
